services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"

  subscription:
    container_name: subscription
    build:
      context: ./server/subscription
    ports:
      - "8080:8080"

  auth:
    container_name: auth
    build:
      context: ./server/auth
    ports:
      - "8000:8000"
    env_file:
      - ./server/auth/.env
  
  notification:
    container_name: notification
    build:
      context: ./server/notification
    ports:
      - "8001:8001"
    env_file:
      - ./server/notification/.env
    depends_on:
      - auth