services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:30"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development


  subscription:
    container_name: subscription
    build:
      context: ./server/subscription
    ports:
      - "8080:8080"

  auth:
    container_name: auth
    build:
      context: ./server/auth
    ports:
      - "8000:8000"
    env_file:
      - ./server/auth/.env
  
  notification:
    container_name: notification
    build:
      context: ./server/notification
    ports:
      - "8001:8001"
    env_file:
      - ./server/notification/.env
    depends_on:
      - auth